export const SUB_LIST_REQUEST = 'SUB_LIST_REQUEST'
export const SUB_LIST_SUCCESS = 'SUB_LIST_SUCCESS'
export const SUB_LIST_FAIL = 'SUB_LIST_FAIL'

export const SUB_DETAILS_REQUEST = 'SUB_DETAILS_REQUEST'
export const SUB_DETAILS_SUCCESS = 'SUB_DETAILS_SUCCESS'
export const SUB_DETAILS_FAIL = 'SUB_DETAILS_FAIL'