# Generated by Django 3.2.5 on 2021-07-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
